
_meta.script_name: train

_base: [demo]

# unit: i

record-step: yes

wandb: no
out-dir: no

# hidden: [2]
max-steps: 10

# env.meaner:
#   _type: meaner

#dataset._type: bernies
dataset._type: mnist

#log.val_accuracy: yes

#events.evaluator:
#  _type: evaluator
#  eval_reporter: null
#  metrics:
#    accuracy: 10

# model:
#   app:
#     input: selection
