# _meta.script_name: train

batch-size: 128

max-steps: 10

dataset._type: mnist

model:
  _type: mlp
  app:
    input: observation
    output: prediction

hidden: [300]
nonlin: relu

env.task._type: classification

# env.eval._type: evaluator

ckpt-freq: 1000

log.accuracy: yes

project-name: demo-{dataset.name}

optimizer._type: adam
