# _meta.script_name: train

batch-size: 128

budget: 10

dataset._type: mnist

model:
  _type: mlp
  app:
    input: observation
    output: prediction

hidden: [300]
nonlin: relu

env.task._type: classification
env.checkpointer:
  _type: checkpointer
  freq: <>ckpt-freq
# env.eval._type: evaluator

ckpt-freq: 1000

log.accuracy: yes

events.monitor:
  _type: wandb
  freqs:
    loss: 5
    accuracy: 5

project-name: demo-{dataset.name}

optimizer._type: adam





